name: Notify Telegram on README Update

on:
  workflow_dispatch:
  push:
    paths:
      - README.md

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get first line of README.md
        id: get_first_line
        run: |
          # Process README.md for TG
          FIRST_LINE=$(head -n 1 README.md | cut -c 3-)
          
          # Read reversed.txt and create Python script
          cat > process_text.py << 'EOF'
          import sys
          import re
          
          def escape_special_chars(text):
              # Read special characters from reversed.txt
              with open('reversed.txt', 'r') as f:
                  special_chars = [line.strip() for line in f if line.strip()]
              
              # Extract URL part to protect it from escaping
              parts = re.split(r'(\(.*?\))', text)
              
              for i in range(len(parts)):
                  # Skip the URL parts (odd indices after split)
                  if i % 2 == 0:
                      # Escape special chars in non-URL parts
                      for char in special_chars:
                          if char not in '[]().':  # Don't escape markdown link syntax
                              parts[i] = parts[i].replace(char, '\\\\' + char)
              
              return ''.join(parts)
          
          # Read input text from first argument
          if len(sys.argv) > 1:
              text = sys.argv[1]
              escaped_text = escape_special_chars(text)
              print(escaped_text)
          EOF
          
          # Run Python script with FIRST_LINE as argument
          CORRECT_TEXT=$(python3 process_text.py "$FIRST_LINE")
          echo "CORRECT_TEXT=$CORRECT_TEXT" >> $GITHUB_ENV

      - name: Send message to Telegram
        if: env.CORRECT_TEXT != ''
        run: |
          curl -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage" \
          -H "Content-Type: application/json" \
          -d '{"chat_id": "${{ secrets.TELEGRAM_CHANNEL_ID }}", "text": "${{ env.CORRECT_TEXT }}", "parse_mode": "MarkdownV2" }'
          # help docs https://core.telegram.org/bots/api#markdownv2-style